sudo: required
dist: trusty
before_install:
- mkdir $HOME/.fonts
- cd $HOME/.fonts
- wget https://github.com/dolbydu/font/raw/master/mono/Courier%20New.ttf
- wget https://github.com/dolbydu/font/raw/master/mono/Courier%20New%20Bold.ttf
- wget https://github.com/dolbydu/font/raw/master/mono/Courier%20New%20Italic.ttf
- wget https://github.com/dolbydu/font/raw/master/mono/Courier%20New%20Bold%20Italic.ttf
- wget https://github.com/dolbydu/font/raw/master/unicode/Microsoft%20Yahei.ttf
- wget https://github.com/dolbydu/font/raw/master/unicode/Microsoft%20Yahei%20Bold.ttf
- fc-cache -f -v
- cd -
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
- mkdir $TRAVIS_BUILD_DIR/_build
- cd tex_version
- xelatex -interaction=nonstopmode -halt-on-error -output-directory ../_build resume_katrina.tex
deploy:
  provider: releases
  api_key:
    secure: LpnepnMok9xbaUI5p5SZMDIO4v9wSoBeASploZpUh6Z90HojXCuQE5hlv3MzLnffBuOdJjTPUM2U1dTUQ282WEezK8zY/0yJWwt+9WVOYL8a5q9Cs2KDoYAu3FRcLc3HpllcUW1kIGP6SiMqOyGgp+md66T9ROK2AVbeqlfvJoAVg4yb6sSNb+BaVcNOHbZ39z0k7Xl2SEVjEoY3IhWspDcUZ/JcOeUzdPilyccgFupWE0rIzeS05tp+7ohjfGRnkNXSP2ZxX+0dthNuSSK4ctqJ82lkxxjFuUt5oaZ6fC6C+A7eMAMjNjgsX0CuuSZe+INbJymqFSOr0g/4hyeYdUoxVXfYR8Vjv5FBzOsiZ4l5CUBdjny5KmW5kZ+gaMh40jxMhbS79iOZ+lgqFlCwJXeEKn9d7SSXbb5GuShj+juR39j51yXdF0wgyRkjsu41jGwCp49z95QM7gQaFWX2hOfD9Lcw4Nqt/XsZTWFLsLa/FPyE8AwnK8pBwb/XLdOn7SsLNtcq4LK2lVp/7bCJNo1KryuOgUHtT+LMS7ntv1RbsCkEmw51P0lxwDmowhCm2rIVVNyUWbhmkd7dfL/p4wUJHDcvRJnYtC+mbfAVvIiIhEpYGhEQSVKHwNk6sqLqK0iBjYtBCboXiuuG9pnUbjeU8T4jk4em88Ma8bL37Zg=
  skip_cleanup: true
  file: $TRAVIS_BUILD_DIR/_build/resume_katrina.pdf
  on:
    repo: katerinaying/resume
